### ISSUE TITLE
解不出来

### ISSUE THREAD

**Issue by pengkebao** [elliotchance/phpserialize#1]
data := `a:3:{i:0;a:2:{i:0;s:6:"白色";i:1;s:6:"黑色";}i:1;a:3:{i:0;s:3:"大";i:1;s:3:"中";i:2;s:3:"小";}i:2;a:2:{i:0;s:3:"女";i:1;s:3:"男";}}`
	var res map[int]map[int]interface{}
	err := phpserialize.Unmarshal([]byte(data), &res)
	fmt.Println(err)
	fmt.Println(res)
can not consume type: a:2:{i:0;s:6:"白色";i:1;s:6:"黑色";}i:1;a:3:{i:0;s:3:"大";i:1;s:3:"中";i:2;s:3:"小";}i:2;a:2:{i:0;s:3:"女";i:1;s:3:"男";}}

**Comment by elliotchance** [comment]
Thank you for raising the issue. I can confirm this will unserialize in PHP 7.

I suspect the bug is here: https://github.com/elliotchance/phpserialize/blob/master/unserialize.go#L25-L40

It is expecting that multibyte characters are encoded as `\x??`. I think this was always true for PHP <7. A check for a multibyte character should fix this.

Would you like to put in a PR for the fix?

**Comment by elliotchance** [comment]
Unfortunately you cannot unmarshalling into a type like `map[int]interface{}` because only `map[interface{}]interface{}` is used internally.

You can use `phpserialize.StringifyKeys` to convert your marshalled result to a more useful `map[string]interface{}`.
